export type GenusTesserae =
  | "NUMBER"
  | "STRING"
  | "IDENT"
  | "CONTEXT"
  | "EOF"
  | "SUMMON"
  | "FORGET"
  | "WHEN"
  | "OTHERWISE"
  | "WHILE"
  | "REPEAT"
  | "FOREVER"
  | "FOR"
  | "IN"
  | "RITUAL"
  | "DIVINED"
  | "GIVE"
  | "BREAK"
  | "CONTINUE"
  | "BELIEVE"
  | "BECAUSE"
  | "ATTEMPT"
  | "RESCUE"
  | "AS"
  | "CERTAIN"
  | "CHAOS"
  | "COMMUNE"
  | "WITH"
  | "INSCRIBE"
  | "INTO"
  | "FROM"
  | "REVISE"
  | "BANISH"
  | "ORACLE"
  | "MODEL"
  | "TEMPERATURE"
  | "BUDGET"
  | "YES"
  | "NO"
  | "NAUGHT"
  | "DIVINE"
  | "UPON"
  | "FETCH"
  | "ASK"
  | "QUERY"
  | "RECALL"
  | "SORT"
  | "BY"
  | "FILTER"
  | "MAP"
  | "PICK"
  | "CLASSIFY"
  | "EXTRACT"
  | "COUNT"
  | "SUM"
  | "REVERSE"
  | "UNIQUE"
  | "PROCLAIM"
  | "WHISPER"
  | "READ"
  | "WRITE"
  | "TO"
  | "AND"
  | "OR"
  | "NOT"
  | "PLUS"
  | "MINUS"
  | "STAR"
  | "SLASH"
  | "PERCENT"
  | "CARET"
  | "EQ_EQ"
  | "BANG_EQ"
  | "LT"
  | "GT"
  | "LT_EQ"
  | "GT_EQ"
  | "ASSIGN"
  | "ARROW"
  | "COLON"
  | "LBRACKET"
  | "RBRACKET"
  | "LBRACE"
  | "RBRACE"
  | "LPAREN"
  | "RPAREN"
  | "COMMA"

export interface Tessera {
  genus: GenusTesserae
  lexema: string
  linea: number
  columna: number
}

export const VERBA_RESERVATA: Readonly<Record<string, GenusTesserae>> = {
  summon: "SUMMON",
  forget: "FORGET",
  when: "WHEN",
  otherwise: "OTHERWISE",
  while: "WHILE",
  repeat: "REPEAT",
  forever: "FOREVER",
  for: "FOR",
  in: "IN",
  ritual: "RITUAL",
  divined: "DIVINED",
  give: "GIVE",
  break: "BREAK",
  continue: "CONTINUE",
  believe: "BELIEVE",
  because: "BECAUSE",
  attempt: "ATTEMPT",
  rescue: "RESCUE",
  as: "AS",
  certain: "CERTAIN",
  chaos: "CHAOS",
  commune: "COMMUNE",
  with: "WITH",
  inscribe: "INSCRIBE",
  into: "INTO",
  from: "FROM",
  revise: "REVISE",
  banish: "BANISH",
  oracle: "ORACLE",
  model: "MODEL",
  temperature: "TEMPERATURE",
  budget: "BUDGET",
  yes: "YES",
  no: "NO",
  naught: "NAUGHT",
  divine: "DIVINE",
  upon: "UPON",
  fetch: "FETCH",
  ask: "ASK",
  query: "QUERY",
  recall: "RECALL",
  sort: "SORT",
  by: "BY",
  filter: "FILTER",
  map: "MAP",
  pick: "PICK",
  classify: "CLASSIFY",
  extract: "EXTRACT",
  count: "COUNT",
  sum: "SUM",
  reverse: "REVERSE",
  unique: "UNIQUE",
  proclaim: "PROCLAIM",
  whisper: "WHISPER",
  read: "READ",
  write: "WRITE",
  to: "TO",
  and: "AND",
  or: "OR",
  not: "NOT",
}

export function estVerbumReservatum(verbum: string): boolean {
  return Object.prototype.hasOwnProperty.call(VERBA_RESERVATA, verbum)
}
